model_class: RandomForest
model_class_type: Classifier

model_kwargs:
  n_estimators: 100
  criterion: gini
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: sqrt
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  bootstrap: True
  oob_score: False
  n_jobs: 8
  random_state: 42
  verbose: 0
  warm_start: False
  class_weight: balanced
  ccp_alpha: 0.0
  max_samples: null

model_search_params:
  n_estimators:
    - 3
    - 4
    - 5
    - 6
    - 8
    - 10
    - 20
    - 40
    - 100
  max_depth:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 8
    - 10
    - 16
  min_samples_split:
    - 2
    - 3
    - 4
  min_samples_leaf:
    - 1
    - 2
    - 3