model_class: XGBoost
model_class_type: Regressor

model_kwargs:
  n_estimators: 100
  booster: gbtree
  learning_rate: 0.01
  gamma: 0.01
  max_depth: 16
  min_child_weight: 1
  colsample_bytree: 1.0

model_search_params:
  n_estimators:
    - 20
    - 40
    - 60
    - 80
    - 100
  learning_rate:
    - 0.01
    - 0.1
    - 0.2
  gamma:
    - 0
    - 0.0001
    - 0.001
    - 0.01
  max_depth:
    - 2
    - 3
    - 4
    - 6
    - 8
    - 10
  colsample_bytree: 
    - 0.4
    - 0.6
    - 0.8
    - 1.0
   