model_class: XGBoost
model_class_type: Classifier

model_kwargs:
  n_estimators: 100
  booster: gbtree
  learning_rate: 0.1
  gamma: 0.05
  max_depth: 8
  min_child_weight: 2
  colsample_bytree: 1.0

model_search_params:
  n_estimators:
    - 20
    - 40
    - 60
    - 80
    - 100
    - 120
    - 150
    - 200
  learning_rate:
    - 0.001
    - 0.01
    - 0.1
  gamma:
    - 0.001
    - 0.005
    - 0.01
    - 0.05
    - 0.1
  max_depth:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 8
    - 10
    - 16
