dataset_class: descriptors

dataset_kwargs:
  acid_descriptor_method: acid_hybrid
  ligand_descriptor_method: ligand_hybrid
  acid_descriptor_kwargs:
    acid_sp_dir: <your_qc_results_dir>/acids_sp
    acid_opt_dir: <your_qc_results_dir>/acids_opt
  ligand_descriptor_kwargs:
    ligand_sp_dir: <your_qc_results_dir>/ligands_sp
    ligand_opt_dir: <your_qc_results_dir>/ligands_opt
  frac_list:
    - 0.8
    - 0.2
  exp_data_path: <your_csv_experiment_data_path>
  acids_path: <your_acids_sdf>
  ligands_path: <your_ligands_sdf>
  root: <a_directory_to_save_dataset>
  select_k: 0 # default as 0 to use all descriptors
  normalize: True # normalize the features
  acid_column_name: Acid Name # column name in <your_csv_experiment_data_path>
  ligand_column_name: Ligand Name # column name in <your_csv_experiment_data_path>
  tag_column_name: Tag
  tag_train: 
  	- 0	# if specified, use the data with Tag in tag_train as training data
  tag_test:
    - 1 # if specified, use the data with Tag in tag_train as training data
  y_column_name: y